# Generated by Django 4.2.3 on 2023-09-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='Image')),
                ('title', models.CharField(max_length=255, verbose_name='Slide Title')),
                ('text', models.TextField(verbose_name='Slide Text')),
            ],
            options={
                'verbose_name': 'General Slider',
                'verbose_name_plural': 'General Slider',
            },
        ),
    ]
